#-----------------[ Yorushika config ]-----------------#
# This is the configuration file of "Wump", all your   #
# sensitive information is stored inside of this file. #
# Do **not** give this file or it's contents to        #
# **anyone**, they can do a lot of bad things with     #
# your tokens. Please be kind and follow the license.  #
# - Wessel                                             #
#------------------------------------------------------#
debug: 4
nightly: true

db: 'mongodb://localhost:27017/Wump'

discord:
  token: '<--snip-->'
  prefix: '!'
  locale: 'en_us'
  enabled: true

  op:
    - '107130754189766656'
  
  playing:
    url: 'https://twitch.tv/wumpusapp'
    name: 'type $help'
    type: 1          # 0 - Playing / 1 - Streaming / 2 - Listening / 3 - Watching
    status: 'online' # online / idle / dnd / invisible

  webhook:
    token: false
    channel: false

  events:
    - ready
    - shardReady
    - shardResume
    - disconnect
    - messageCreate
    - messageDelete
    - guildMemberAdd
    - shardDisconnect

  commands:
    - yorushika.core.locale
    - yorushika.core.prefix
    - yorushika.utility.*
    - yorushika.information.*
    - yorushika.image.*
    - yorushika.tags.*
    - yorushika.games.*
    - yorushika.developer.*

api:
  lol: '<--snip-->'
  dbl: '<--snip-->'
  ksoft: '<--snip-->'